### ISSUE TITLE
Write an initial technical report

### ISSUE THREAD

**Issue by tumrod** [tumrod/cs373-idb#16]
Write an initial technical report using a GitHub Wiki.
The audience comprises other software developers, as opposed to users.
For this phase it must be at least 2500 words.
Document the RESTful API and the models well.
Format the report clearly, attractively, and consistently, using good headers, figures, and grammar.

| Section | Features |
| --- | --- |
| Title | The group name. |
|  | The group members. |
| Introduction | What is the problem? |
|  | What are the use cases? |
| Design | RESTful API |
|  | DB models |
| Tests | unit tests of the models |
| Other | Proof-read your report. Get another group to read it. Read it aloud. |
|  | Create diagrams with captions. |
|  | Create sections and subsections effectively. |

**Comment by rcwong** [comment]
currently we only have ~2192 words
