### ISSUE TITLE
About page info for each member

### ISSUE THREAD

**Issue by tumrod** [tumrod/cs373-idb#28]
For each member, I need these from y'all:
Bio: just about one sentence about you guys, maybe hobby or fun fact?
and also picture of you (push it in static/img/team/)
Thanks

**Comment by atxmemo** [comment]
@tumrod 

Son, brother, friend, student, cooking and travel enthusiast.

**Comment by rcwong** [comment]
@tumrod 

Rachel enjoys ultimate frisbee, soccer, beerio kart, and long walks on the beach.

**Comment by noelleryanhall** [comment]
added my photo

**Comment by noelleryanhall** [comment]
is currently binge watching all 366 episodes of law and order: svu
